version: '3.8'


services:
  dashy:
    image: lissy93/dashy:latest
    volumes:
      - dashy_data:/app/public/data
      - ./conf.yml:/app/user-data/conf.yml
    ports:
      - "80:8080"
    environment:
      - CONF_HASH=d149e171d2da6259fa9999fb064e1137dfac40c44d1cecf8750cadead549b92b
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: pause

volumes:
  dashy_data:
