version: '3.2'

services:
  dashy:
    image: lissy93/dashy:latest
    volumes:
      - dashy_data:/app/public/data
    networks:
      - proxy
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

volumes:
  dashy_data:

networks:
  proxy:
    external: true