version: '3.8'

services:
  dashy:
    image: lissy93/dashy:latest
    volumes:
      - dashy_data:/app/public/data
      - ./conf.yml:/app/user-data/conf.yml
    ports:
      - "1313:8080"
    environment:
      - CONF_HASH=5d9cd50309748786dac6fdcba2a13814035b217f5e45735aba87508560933453
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 360s
        order: start-first
        failure_action: rollback
        monitor: 120s  # Surveille pendant 2 minutes après le déploiement
      rollback_config:
        parallelism: 1
        delay: 360s
        order: start-first
        failure_action: pause
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashy.rule=Host(`dashy.fervantfactory.delpeuch.net`)
        - traefik.http.routers.dashy.entrypoints=web
        - traefik.http.services.dashy.loadbalancer.server.port=8080
    networks:
      - proxy

volumes:
  dashy_data:

networks:
  proxy:
    external: true
