version: '3.8'

services:
  dashy:
    image: lissy93/dashy:latest
    volumes:
      - dashy_data:/app/public/data
      - ./conf.yml:/app/user-data/conf.yml
      - ./theme.css:/app/user-data/theme.css
    ports:
      - "1313:8080"
    environment:
      - CONF_HASH=0a01a02d952972336941d4a8a1dcd64b660fbe3a2ab48c08919ba113aa85e02f
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 360s
        order: start-first
        failure_action: rollback
        monitor: 120s  # Surveille pendant 2 minutes après le déploiement
      rollback_config:
        parallelism: 1
        delay: 360s
        order: start-first
        failure_action: pause
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashy.rule=Host(`dashy.fervantfactory.delpeuch.net`)
        - traefik.http.routers.dashy.entrypoints=websecure
        - traefik.http.routers.dashy.tls.certresolver=gandi
        - traefik.http.services.dashy.loadbalancer.server.port=8080
    networks:
      - proxy

volumes:
  dashy_data:

networks:
  proxy:
    external: true
