version: '3.8'


services:
  dashy:
    image: lissy93/dashy:latest
    volumes:
      - dashy_data:/app/public/data
      - ./conf.yml:/app/user-data/conf.yml
    ports:
      - "80:8080"
    environment:
      - CONF_HASH=8d67bf398195f1c917102646301bf4ef248a7101169c8e42482ab8c0472ee26c
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 360s
        order: start-first
        failure_action: rollback
        monitor: 120s  # Surveille pendant 2 minutes après le déploiement
      rollback_config:
        parallelism: 1
        delay: 360s
        order: start-first
        failure_action: pause

volumes:
  dashy_data:
