services:
  tailscale-dashy:
    image: tailscale/tailscale:latest
    hostname: dashy
    environment:
      - TS_AUTHKEY=tskey-auth-kL5BCYCLDD11CNTRL-zLW3ekS2FT7kYA48mfMTT73fPfL9HxT4
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-dashy/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  nginx-dashy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: service:tailscale-dashy
  dashy:
    image: lissy93/dashy:latest
    volumes:
      - dashy_data:/app/public/data
    network_mode: service:tailscale-dashy

volumes:
  dashy_data: