mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

record:
  enabled: true
  continuous:
    days: 0
  motion:
    days: 0
  alerts:
    retain:
      days: 7
      mode: all
  detections:
    retain:
      days: 7
      mode: motion

objects:
  track:
    - person

cameras:     # No cameras defined, UI wizard should be used
  cam_dcf2d3a8:
    enabled: true
    friendly_name: Tapo entrée
    ffmpeg:
      inputs:
        - path: rtsp://sedelpeuch:azertyuiop@192.168.1.27:554/stream1
          roles:
            - detect
            - record
            - audio
    detect:
      width: 1280
      height: 720
      enabled: true
    record:
      enabled: true
      continuous:
        days: 0
      motion:
        days: 0
      alerts:
        retain:
          days: 7
          mode: all
      detections:
        retain:
          days: 7
          mode: motion
    live:
      streams:
        Stream 1: cam_dcf2d3a8
version: 0.17-0
go2rtc:
  streams:
    cam_dcf2d3a8:
      - rtsp://sedelpeuch:azertyuiop@192.168.1.27:554/stream1
semantic_search:
  enabled: true
  model_size: small
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: false
