version: "3.8"

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate_config:/config
      - ./frigate-config.yaml:/config/config.yaml
      - frigate_storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 100000000
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1000000000
    ports:
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "5000:5000"
    environment:
      FRIGATE_RTSP_PASSWORD: "admin"
      CONFIG_HASH: "09b576f717713640c058aaa711b319264226789f08059117bcb179195774e107"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frigate.rule=Host(`frigate.fervantfactory.delpeuch.net`)"
        - "traefik.http.routers.frigate.entrypoints=websecure"
        - "traefik.http.routers.frigate.tls.certresolver=gandi"
        - "traefik.http.services.frigate.loadbalancer.server.port=5000"

volumes:
  frigate_config:
    driver: local
  frigate_storage:
    driver: local

networks:
  proxy:
    external: true
