version: '3.8'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - "8123:8123"  # Interface web
      - "1400:1400/udp"  # SSDP
      - "5353:5353/udp"  # mDNS
      - "51827:51827/tcp"  # HomeKit
    networks:
      - ha_network
    environment:
      - TZ=Europe/Paris
    volumes:
      - homeassistant_data:/config
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager  # Ou spécifiez un nœud spécifique avec node.hostname == votrehote

networks:
  ha_network:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  homeassistant_data:
    driver: local
