version: '3.8'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - "8123:8123"  # Interface web
    environment:
      - TZ=Europe/Paris
    volumes:
      - homeassistant_data:/config
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 360s
        order: start-first
        failure_action: rollback
        monitor: 120s  # Surveille pendant 2 minutes après le déploiement
      rollback_config:
        parallelism: 1
        delay: 360s
        order: start-first
        failure_action: pause
      placement:
        constraints:
          - node.role == manager

volumes:
  homeassistant_data:
    driver: local
