version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - proxy

volumes:
  nginx_conf:
    driver: local

networks:
  proxy:
    external: true
