version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Important: montez dans conf.d
    networks:
      - proxy
    ports:
      - "80:80"

networks:
  proxy:
    external: true